import Link from 'next/link'
import PublicShell from '@/components/PublicShell'
export default function AgentsPage() {
  return <PublicShell><main className="public-main">
    <section className="meet-intro"><p className="eyebrow">Your network, with your agent</p><h1>Connect your agent.</h1><p>Search public people now, or connect your account to search your own network. No LinkedIn export is required to connect.</p></section>
    <div className="hero-actions"><a className="public-button public-button-primary" href="https://id.ideaflow.app/agents?app=unlinked">Connect with Ideaflow</a><Link className="public-button public-button-quiet" href="/search-public">Search public people</Link></div>
    <section className="steps"><div><h2>One connection, your choice of apps.</h2><p className="section-copy">The shared Ideaflow connector covers Unlinked, OpenChat and Thoughtstream Vision with separate permissions. Choose only the access you need.</p><p className="section-copy"><a href="https://id.ideaflow.app/agents/guide">Agent setup guide</a> covers ChatGPT and dots, Meta Muse, Claude, Codex, Gemini CLI, Cursor and other agents. It distinguishes documented setup methods from verified connections.</p></div><ol>
      <li><span>01</span><div><h3>Use your agent’s setup route</h3><p>Dots use installed plugins and OAuth. Muse can create a custom API connector from our <a href="/openapi.json">API description</a>, using a revocable Unlinked credential through its credential setup. Actual host acceptance remains unverified.</p></div></li>
      <li><span>02</span><div><h3>Authorize your account</h3><p>Confirm the account and the app permissions. Reading a setup page or copying a prompt does not install or authorize a connector.</p></div></li>
      <li><span>03</span><div><h3>Verify a read-only query</h3><p>Your agent should check identity and available access, then run a query. Missing permissions, pending imports and zero search matches are different states. Check existing data before requesting an export.</p></div></li>
    </ol></section>
    <p className="section-copy">Existing direct Unlinked MCP connections remain supported at https://www.unlinked.ai/mcp. API clients can manage their service-specific grant in <a href="https://www.unlinked.ai/settings">Unlinked Settings</a>. Unlinked grants cannot send OpenChat messages. In Settings → API keys, Copy API key gives the raw credential for a key/access-token field, without a Bearer prefix or JSON; only a full Authorization-header field takes Bearer followed by one space and the key. Show/Hide and copy remain available without replacing the key. Create API key makes a named independent key; Copy agent setup copies the selected key’s MCP configuration for compatible clients.</p>
    <p className="section-copy">Public search needs no login or archive; web-reader access must be checked in the actual agent. To add your own contacts when needed, see <Link href="/import-linkedin">import instructions</Link>.</p>
  </main></PublicShell>
}
